### ISSUE TITLE
How to use MCP with Ollama. 

### ISSUE THREAD

**Issue by Lyansun** [mark3labs/mcp-go#11]
Hey, I just watched your video on YouTube—it’s amazing! However, I couldn’t find how to configure the interaction with the local Ollama in your code. Could you please explain it in more detail? Thanks a lot!

**Comment by ezynda3** [comment]
https://github.com/mark3labs/mcphost works with ollama out of the box. Please check out the readme.

Cheers!

**Comment by Lyansun** [comment]
👍Cool!
